DROP TABLE Predicao CASCADE CONSTRAINTS;
DROP TABLE Imagem CASCADE CONSTRAINTS;
DROP TABLE DadosProducao CASCADE CONSTRAINTS;
DROP TABLE DadosClimaticos CASCADE CONSTRAINTS;
DROP TABLE Colheita CASCADE CONSTRAINTS;
DROP TABLE Fazenda CASCADE CONSTRAINTS;


CREATE TABLE Predicao (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    colheita_id NUMBER,
    fazenda_id NUMBER,
    data_predicao DATE,
    qtd_prevista NUMBER,
    CONSTRAINT fk_colheita_predicao FOREIGN KEY (colheita_id) REFERENCES Colheita(id),
    CONSTRAINT fk_fazenda_predicao FOREIGN KEY (fazenda_id) REFERENCES Fazenda(id)
);

CREATE TABLE Imagem (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(255),
    tipo VARCHAR2(50),
    dados BLOB,
    data_upload TIMESTAMP
);

CREATE TABLE Fazenda (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    dono VARCHAR2(255),
    latitude VARCHAR2(50),
    longitude VARCHAR2(50),
    tamanho NUMBER
);

CREATE TABLE DadosProducao (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    colheita_id NUMBER,
    data_colheita DATE,
    qtd_produzida NUMBER,
    lista_fertilizantes CLOB, -- Será armazenado como um CLOB para armazenar strings longas
    CONSTRAINT fk_colheita_dadosproducao FOREIGN KEY (colheita_id) REFERENCES Colheita(id)
);

CREATE TABLE DadosClimaticos (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    data_local DATE,
    temperatura_graus NUMBER(5, 2), -- Temperatura com precisão
    umidade NUMBER,
    precipitacao NUMBER(5, 2), -- Precipitação com precisão
    fazenda_id NUMBER,
    CONSTRAINT fk_fazenda_dadosclimaticos FOREIGN KEY (fazenda_id) REFERENCES Fazenda(id)
);

CREATE TABLE Colheita (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(255),
    tipo VARCHAR2(50),
    estacao_do_ano VARCHAR2(50),
    fazenda_id NUMBER,
    CONSTRAINT fk_fazenda_colheita FOREIGN KEY (fazenda_id) REFERENCES Fazenda(id)
);

CREATE SEQUENCE fazenda_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE colheita_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE predicao_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE imagem_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE dados_producao_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE dados_climaticos_seq START WITH 1 INCREMENT BY 1;

INSERT INTO Fazenda (id, dono, latitude, longitude, tamanho) VALUES (fazenda_seq.NEXTVAL, 'João Silva', '-22.1234', '-47.5678', 150);
INSERT INTO Fazenda (id, dono, latitude, longitude, tamanho) VALUES (fazenda_seq.NEXTVAL, 'Maria Souza', '-23.9876', '-48.6543', 200);

INSERT INTO Colheita (id, nome, tipo, estacao_do_ano, fazenda_id) VALUES (colheita_seq.NEXTVAL, 'Milho', 'Cereal', 'Primavera', 1);
INSERT INTO Colheita (id, nome, tipo, estacao_do_ano, fazenda_id) VALUES (colheita_seq.NEXTVAL, 'Soja', 'Grão', 'Verão', 2);

INSERT INTO Predicao (id, colheita_id, fazenda_id, data_predicao, qtd_prevista) VALUES (predicao_seq.NEXTVAL, 1, 1, TO_DATE('2024-09-15', 'YYYY-MM-DD'), 1200);
INSERT INTO Predicao (id, colheita_id, fazenda_id, data_predicao, qtd_prevista) VALUES (predicao_seq.NEXTVAL, 2, 2, TO_DATE('2024-10-20', 'YYYY-MM-DD'), 1500);

INSERT INTO Imagem (id, nome, tipo, dados, data_upload) VALUES (imagem_seq.NEXTVAL, 'Imagem1.jpg', 'image/jpeg', EMPTY_BLOB(), SYSTIMESTAMP);
INSERT INTO Imagem (id, nome, tipo, dados, data_upload) VALUES (imagem_seq.NEXTVAL, 'Imagem2.jpg', 'image/png', EMPTY_BLOB(), SYSTIMESTAMP);

INSERT INTO DadosProducao (id, colheita_id, data_colheita, qtd_produzida, lista_fertilizantes) 
VALUES (dados_producao_seq.NEXTVAL, 1, TO_DATE('2024-03-01', 'YYYY-MM-DD'), 1000, 'Nitrogênio, Potássio');
INSERT INTO DadosProducao (id, colheita_id, data_colheita, qtd_produzida, lista_fertilizantes) 
VALUES (dados_producao_seq.NEXTVAL, 2, TO_DATE('2024-03-10', 'YYYY-MM-DD'), 800, 'Fósforo, Cálcio');

INSERT INTO DadosClimaticos (id, data_local, temperatura_graus, umidade, precipitacao, fazenda_id) 
VALUES (dados_climaticos_seq.NEXTVAL, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 25.5, 75, 100.2, 1);
INSERT INTO DadosClimaticos (id, data_local, temperatura_graus, umidade, precipitacao, fazenda_id) 
VALUES (dados_climaticos_seq.NEXTVAL, TO_DATE('2024-02-15', 'YYYY-MM-DD'), 22.3, 60, 50.5, 2);

SELECT * FROM Fazenda;
SELECT * FROM Colheita;
SELECT * FROM Predicao;
SELECT id, nome, tipo, data_upload FROM Imagem;
SELECT * FROM DadosProducao;
SELECT * FROM DadosClimaticos;


